---
/**:
  ros__parameters:
    # The client_id to be set in smart_access_config.json, must be a unique integer.
      master_client_id: 1000
      # This sets the dev_id in the hw_inventory.json
      hw_dev_id: 2
      # This sets the port in the hw_inventory.json
      hw_port: 55555
      # This sets the iface_name in the hw_inventory.json
      hw_iface_name: "eno1"
      # An array of sensors to subscribe to.
      sensors:
          # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
          # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
          sensor_0:
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 100
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.0"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_1:
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 101
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.1"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_2:
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 102
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.2"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_3:
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 103
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.3"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_4:
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 104
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.4"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_5:   
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 105
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.5"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_6:       
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 106
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.6"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_7:       
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 107
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.7"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_8:       
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 108
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.8"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_9:       
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 109
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.9"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_10:       
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 110
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.10"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10
          sensor_11:       
              # The model of the connected sensor.
              model: "umrr96"
              # The client_id of the sensor/source, must be a unique integer.
              id: 111
              # The ip address of the sensor or of the source acting as a sensor.
              ip: "192.168.11.11"
              # The port to be used.
              port: 55555
              # The frame_id to be set to the published messages.
              frame_id: "umrr"
              # Specify the history size.
              history_size: 10